import type { LevelDef } from "../types";

// World 2 — Voltgrid City: gravity inversion, reverse zones, laser gates, portals.

export const world2: LevelDef[] = [
  {
    id: "w2-1",
    world: 2,
    index: 1,
    name: "Upside Down",
    ruleTaught: "Purple fields flip your gravity — walk into one.",
    rows: [
      "##########................",
      "##########................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    gravityZones: [{ x: 10, y: 0, w: 5, h: 7 }],
    shards: [{ id: "s1", x: 12, y: 1 }],
    parTime: 11,
  },
  {
    id: "w2-2",
    world: 2,
    index: 2,
    name: "Ceiling Run",
    ruleTaught: "While flipped, spikes on the floor are safe — but the ceiling isn't.",
    twist: "The gravity field ends mid-air. Land before it does.",
    rows: [
      "##########################",
      "SS......................SS",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###SSSS##############SS###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 23, y: 5 },
    gravityZones: [{ x: 7, y: 0, w: 10, h: 7 }],
    shards: [{ id: "s1", x: 11, y: 1 }],
    parTime: 13,
  },
  {
    id: "w2-3",
    world: 2,
    index: 3,
    name: "Backwards Day",
    ruleTaught: "Pink fog reverses your controls.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    reverseZones: [{ x: 9, y: 0, w: 8, h: 7 }],
    shards: [{ id: "s1", x: 12, y: 5 }],
    parTime: 12,
  },
  {
    id: "w2-4",
    world: 2,
    index: 4,
    name: "Mirror Nerve",
    ruleTaught: "Reverse fog over a fake platform means you must think in reverse twice.",
    twist: "The exit sits just past a fake ledge, inside the fog.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.####~~~~####..........",
      "###.####~~~~####......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    reverseZones: [{ x: 15, y: 0, w: 8, h: 7 }],
    shards: [{ id: "s1", x: 6, y: 4 }],
    parTime: 14,
  },
  {
    id: "w2-5",
    world: 2,
    index: 5,
    name: "Laser Curtain",
    ruleTaught: "Red beams pulse on a rhythm — count the beat before you run.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    laserGates: [{ id: "l1", x: 12, y: 1, h: 6, axis: "vertical", onTime: 1.1, offTime: 1.1 }],
    shards: [{ id: "s1", x: 8, y: 5 }, { id: "s2", x: 18, y: 5 }],
    parTime: 12,
  },
  {
    id: "w2-6",
    world: 2,
    index: 6,
    name: "Portal Shortcut",
    ruleTaught: "Step into a cyan ring, exit the paired magenta ring.",
    twist: "The portal drops you right next to a laser gate — keep moving.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P..####........####.....",
      "###..####........####..###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    portals: [
      { id: "p1", x: 7, y: 4, linkId: "p2", color: "cyan" },
      { id: "p2", x: 18, y: 4, linkId: "p1", color: "magenta" },
    ],
    laserGates: [{ id: "l1", x: 20, y: 1, h: 6, axis: "vertical", onTime: 0.9, offTime: 1.3 }],
    shards: [{ id: "s1", x: 22, y: 5 }],
    parTime: 13,
  },
  {
    id: "w2-7",
    world: 2,
    index: 7,
    name: "Gravity Gauntlet",
    ruleTaught: "Combine flips and fog — the run is longer, the rules stack.",
    twist: "Flip fields chain back-to-back with no rest between them.",
    rows: [
      "##########........########",
      "##########........########",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    gravityZones: [
      { x: 8, y: 0, w: 4, h: 7 },
      { x: 16, y: 0, w: 4, h: 7 },
    ],
    reverseZones: [{ x: 12, y: 0, w: 4, h: 7 }],
    shards: [{ id: "s1", x: 10, y: 1 }, { id: "s2", x: 18, y: 1 }],
    parTime: 16,
  },
];
