import type { LevelDef } from "../types";

// World 1 — Neon Foundry: teaches the fundamentals, then twists them.
// Grid legend: '#' solid, '.' empty, 'S' spike, '~' fake platform (looks solid, has no collision)

export const world1: LevelDef[] = [
  {
    id: "w1-1",
    world: 1,
    index: 1,
    name: "First Steps",
    ruleTaught: "Run and jump across the gap.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....####....####...####",
      "###....####....####...####",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 9, y: 4 }, { id: "s2", x: 16, y: 4 }],
    parTime: 8,
  },
  {
    id: "w1-2",
    world: 1,
    index: 2,
    name: "Solid Ground",
    ruleTaught: "Bright tiles are always safe to stand on.",
    twist: "But not everything that looks solid... is.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P..####..##~~..####..###",
      "###..####..##~~..####..###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    shards: [{ id: "s1", x: 12, y: 4 }],
    parTime: 9,
  },
  {
    id: "w1-3",
    world: 1,
    index: 3,
    name: "Watch Your Step",
    ruleTaught: "Fake platforms look identical to real ones — memorize, don't guess.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.####~~~~####~~~~####..",
      "###.####~~~~####~~~~####.#",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 25, y: 5 },
    shards: [{ id: "s1", x: 6, y: 4 }, { id: "s2", x: 14, y: 4 }, { id: "s3", x: 22, y: 4 }],
    parTime: 12,
  },
  {
    id: "w1-4",
    world: 1,
    index: 4,
    name: "Sliding Doors",
    ruleTaught: "Time your run past the moving wall.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###################...####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    movingWalls: [{ id: "mw1", x: 12, y: 1, w: 1, h: 5, axis: "y", range: 4, speed: 1.6 }],
    shards: [{ id: "s1", x: 8, y: 5 }],
    parTime: 10,
  },
  {
    id: "w1-5",
    world: 1,
    index: 5,
    name: "Double Trouble",
    ruleTaught: "Two walls, two rhythms — read them both.",
    twist: "The second wall moves twice as fast as the first.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###..............#....####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    movingWalls: [
      { id: "mw1", x: 9, y: 1, w: 1, h: 5, axis: "y", range: 4, speed: 1.2 },
      { id: "mw2", x: 17, y: 1, w: 1, h: 5, axis: "y", range: 4, speed: 2.4, phase: 0.5 },
    ],
    shards: [{ id: "s1", x: 13, y: 5 }, { id: "s2", x: 21, y: 5 }],
    parTime: 13,
  },
  {
    id: "w1-6",
    world: 1,
    index: 6,
    name: "Trust Fall",
    ruleTaught: "Checkpoints save your progress — step on the glowing beacon.",
    twist: "One beacon looks the same but does nothing at all.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P..####~~~~####~~~~####.",
      "###..####~~~~####~~~~####.",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 25, y: 5 },
    checkpoints: [{ id: "c1", x: 13, y: 4 }],
    fakeCheckpoints: [{ id: "fc1", x: 6, y: 4 }],
    shards: [{ id: "s1", x: 20, y: 4 }],
    parTime: 14,
  },
];
