import type { LevelDef } from "../types";

// World 5 — Dark Reactor: steam vents (telegraphed vertical jets) layered onto
// existing mechanics. Every level teaches one new wrinkle on top of last world's toolkit.

export const world5: LevelDef[] = [
  {
    id: "w5-1",
    world: 5,
    index: 1,
    name: "First Hiss",
    ruleTaught: "A hiss and glow mean a steam jet is about to erupt. Wait it out, then dash through.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    steamVents: [{ id: "v1", x: 12, y: 6, h: 4, warnTime: 0.8, activeTime: 0.6, cooldownTime: 1.4 }],
    shards: [{ id: "s1", x: 12, y: 2 }],
    parTime: 12,
  },
  {
    id: "w5-2",
    world: 5,
    index: 2,
    name: "Double Vent",
    ruleTaught: "Two vents, offset timing — cross while one is cooling and the other hasn't warned yet.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    steamVents: [
      { id: "v1", x: 10, y: 6, h: 4, warnTime: 0.8, activeTime: 0.6, cooldownTime: 1.6, phase: 0 },
      { id: "v2", x: 16, y: 6, h: 4, warnTime: 0.8, activeTime: 0.6, cooldownTime: 1.6, phase: 0.5 },
    ],
    shards: [{ id: "s1", x: 13, y: 2 }],
    parTime: 14,
  },
  {
    id: "w5-3",
    world: 5,
    index: 3,
    name: "Vent & Blade",
    ruleTaught: "A steam vent under a rotating saw — read both rhythms at once.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    steamVents: [{ id: "v1", x: 14, y: 6, h: 4, warnTime: 0.7, activeTime: 0.6, cooldownTime: 1.3 }],
    rotatingPlatforms: [{ id: "r1", cx: 19, cy: 4, radius: 3, speed: 1.3, armLen: 2 }],
    shards: [{ id: "s1", x: 9, y: 5 }],
    parTime: 16,
  },
  {
    id: "w5-4",
    world: 5,
    index: 4,
    name: "Reactor Gauntlet",
    ruleTaught: "Three vents in a row force a stop-start rhythm through the corridor.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    steamVents: [
      { id: "v1", x: 8, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3, phase: 0 },
      { id: "v2", x: 13, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3, phase: 0.33 },
      { id: "v3", x: 18, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3, phase: 0.66 },
    ],
    shards: [{ id: "s1", x: 10, y: 5 }, { id: "s2", x: 20, y: 5 }],
    parTime: 18,
  },
  {
    id: "w5-5",
    world: 5,
    index: 5,
    name: "Molten Dark",
    ruleTaught: "Steam vents inside a dark zone — the hiss/glow still telegraphs even when you can barely see.",
    twist: "Stay near the torch light; the vent's glow cuts through the dark just enough to read it.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    darkZones: [
      {
        id: "d1",
        x: 6,
        y: 0,
        w: 10,
        h: 7,
        bridgeTiles: [
          { x: 7, y: 5 },
          { x: 9, y: 5 },
          { x: 11, y: 5 },
          { x: 13, y: 5 },
        ],
      },
    ],
    steamVents: [{ id: "v1", x: 10, y: 6, h: 4, warnTime: 0.75, activeTime: 0.55, cooldownTime: 1.4 }],
    shards: [{ id: "s1", x: 9, y: 3 }],
    parTime: 19,
  },
  {
    id: "w5-6",
    world: 5,
    index: 6,
    name: "Reactor Meltdown",
    ruleTaught: "Everything from Dark Reactor, back to back — no new tricks, just precision.",
    twist: "The final vent syncs with the laser gate — only one safe beat per cycle.",
    rows: [
      "##########................",
      "##########................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    steamVents: [
      { id: "v1", x: 9, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3, phase: 0 },
      { id: "v2", x: 20, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3, phase: 0.5 },
    ],
    laserGates: [{ id: "l1", x: 15, y: 1, h: 6, axis: "vertical", onTime: 1, offTime: 1.2 }],
    rotatingPlatforms: [{ id: "r1", cx: 12, cy: 4, radius: 2.5, speed: 1.2, armLen: 2 }],
    shards: [{ id: "s1", x: 11, y: 1 }, { id: "s2", x: 22, y: 5 }],
    parTime: 22,
  },
];
