import type { LevelDef } from "../types";

// World 7 — Chaos Rift: the finale world. Chaos rifts are safe zones that apply
// either gravity-flip or reverse-controls, randomized once per attempt, so players
// must react on the fly rather than memorize a fixed layout. Combined with every
// mechanic from Worlds 1-6 for the hardest, most memorable challenges in the game.

export const world7: LevelDef[] = [
  {
    id: "w7-1",
    world: 7,
    index: 1,
    name: "Unstable Ground",
    ruleTaught: "A chaos rift is safe to touch, but it randomly flips gravity or reverses your controls for the run. Adapt fast.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [{ id: "c1", x: 10, y: 0, w: 6, h: 7 }],
    shards: [{ id: "s1", x: 13, y: 1 }],
    parTime: 13,
  },
  {
    id: "w7-2",
    world: 7,
    index: 2,
    name: "Double Tear",
    ruleTaught: "Two rifts back to back — each rolls its own effect independently.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [
      { id: "c1", x: 6, y: 0, w: 5, h: 7 },
      { id: "c2", x: 16, y: 0, w: 5, h: 7 },
    ],
    shards: [{ id: "s1", x: 8, y: 1 }, { id: "s2", x: 18, y: 5 }],
    parTime: 16,
  },
  {
    id: "w7-3",
    world: 7,
    index: 3,
    name: "Rift & Vent",
    ruleTaught: "A chaos rift right before a steam vent — whichever effect you get changes how you dodge the jet.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [{ id: "c1", x: 8, y: 0, w: 5, h: 7 }],
    steamVents: [{ id: "v1", x: 17, y: 6, h: 4, warnTime: 0.75, activeTime: 0.55, cooldownTime: 1.4 }],
    shards: [{ id: "s1", x: 20, y: 5 }],
    parTime: 18,
  },
  {
    id: "w7-4",
    world: 7,
    index: 4,
    name: "Firewall Chaos",
    ruleTaught: "A rift feeding straight into a firewall sweep — whichever controls you get, the safe gap doesn't move.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [{ id: "c1", x: 7, y: 0, w: 5, h: 7 }],
    firewallSweeps: [{ id: "f1", startX: 14, endX: 21, y: 2, h: 3, chargeTime: 1, sweepTime: 1.3 }],
    shards: [{ id: "s1", x: 10, y: 5 }],
    parTime: 20,
  },
  {
    id: "w7-5",
    world: 7,
    index: 5,
    name: "Full Spectrum",
    ruleTaught: "Rift, saw, mimic, and laser in one room — read the space, not just the rift.",
    twist: "The mimic waits exactly where a gravity flip would land you — check both floor and ceiling.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [{ id: "c1", x: 6, y: 0, w: 5, h: 7 }],
    rotatingPlatforms: [{ id: "r1", cx: 14, cy: 3, radius: 3, speed: 1.3, armLen: 2 }],
    laserGates: [{ id: "l1", x: 18, y: 1, h: 6, axis: "vertical", onTime: 1, offTime: 1.2 }],
    mimicEnemies: [{ id: "m1", x: 21, y: 5, triggerRadius: 3, lungeSpeed: 270 }],
    shards: [{ id: "s1", x: 9, y: 1 }],
    parTime: 24,
  },
  {
    id: "w7-6",
    world: 7,
    index: 6,
    name: "The Last Rift",
    ruleTaught: "The final gauntlet — rifts, vents, firewalls, saws, and lasers, all at once.",
    twist: "Three rifts in sequence, each re-rolled independently — no two runs play quite the same.",
    rows: [
      "##########................",
      "##########................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    chaosRifts: [
      { id: "c1", x: 8, y: 0, w: 3, h: 7 },
      { id: "c2", x: 13, y: 0, w: 3, h: 7 },
      { id: "c3", x: 18, y: 0, w: 3, h: 7 },
    ],
    steamVents: [{ id: "v1", x: 10, y: 6, h: 4, warnTime: 0.7, activeTime: 0.5, cooldownTime: 1.3 }],
    firewallSweeps: [{ id: "f1", startX: 15, endX: 21, y: 1, h: 3, chargeTime: 0.9, sweepTime: 1.1 }],
    rotatingPlatforms: [{ id: "r1", cx: 22, cy: 4, radius: 2, speed: 1.4, armLen: 2 }],
    shards: [{ id: "s1", x: 9, y: 1 }, { id: "s2", x: 19, y: 1 }],
    parTime: 26,
  },
];
