import type { LevelDef } from "../types";

// World 1 — Neon Foundry: teaches fundamentals cleanly, then adds one new
// mechanic per level. Every gap here is jumpable at half-charge, so quick
// taps + full holds both feel viable (variable jump height is the star).
// Grid legend:
//   '#' solid   '.' empty   'S' spike   '~' fake platform (looks solid, isn't)
//   'B' bounce pad (super-jump)   '>' / '<' speed pad (arrow direction)
//   'I' ice/slippery surface       'L' lava/fire (instant lethal on touch)
//   'P' player-start marker (visual only — real spawn comes from `playerStart`)

export const world1: LevelDef[] = [
  {
    id: "w1-1",
    world: 1,
    index: 1,
    name: "First Steps",
    ruleTaught: "Tap right to run, tap jump to hop.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "########....########....##",
      "########....########....##",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 12, y: 3 }],
    parTime: 10,
  },
  {
    id: "w1-2",
    world: 1,
    index: 2,
    name: "Solid Ground",
    ruleTaught: "Bright tiles are always safe to stand on.",
    twist: "But not everything that looks solid... is.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "...........~~~~...........",
      "..P.......................",
      "########..########..######",
      "########..########..######",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 13, y: 2 }],
    parTime: 12,
  },
  {
    id: "w1-3",
    world: 1,
    index: 3,
    name: "Spike Alley",
    ruleTaught: "Red spikes hurt. Jump over the pits.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "########..########..######",
      "########SS########SS######",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 20, y: 3 }],
    parTime: 12,
  },
  {
    id: "w1-4",
    world: 1,
    index: 4,
    name: "Hold to Fly",
    ruleTaught: "Hold jump longer to jump higher.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..............####........",
      "..P.....####..............",
      "###.......##.......###..##",
      "#####.....##.....##########",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 15, y: 2 }],
    parTime: 14,
  },
  {
    id: "w1-5",
    world: 1,
    index: 5,
    name: "Bounce On Up",
    ruleTaught: "Yellow pads launch you sky-high.",
    rows: [
      "..........................",
      "..................####....",
      "..........................",
      "..........................",
      "..P.......................",
      "########B##########....####",
      "##########################",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 19, y: 0 }],
    parTime: 14,
  },
  {
    id: "w1-6",
    world: 1,
    index: 6,
    name: "Fast Track",
    ruleTaught: "Cyan chevrons rocket you across gaps.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "####>>>>....####....######",
      "########....####..########",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 10, y: 3 }],
    parTime: 10,
  },
  {
    id: "w1-7",
    world: 1,
    index: 7,
    name: "Fake or Foe",
    ruleTaught: "Trust bright tiles. Doubt everything else.",
    rows: [
      "..........................",
      "..........................",
      "........~~~~..............",
      "..............~~~~........",
      "..P.......................",
      "########..####....####..##",
      "########..####....####..##",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 10, y: 1 }],
    parTime: 14,
    fakeCheckpoints: [{ x: 15, y: 3 }],
  },
  {
    id: "w1-8",
    world: 1,
    index: 8,
    name: "Foundry Finale",
    ruleTaught: "Everything you've learned — string it together.",
    rows: [
      "..........................",
      "..........................",
      "...............~~~~.......",
      "..........................",
      "..P.......................",
      "####B.####>>>>####..######",
      "####..####....####..######",
    ],
    playerStart: { x: 2, y: 4 },
    exit: { x: 24, y: 4 },
    shards: [{ id: "s1", x: 17, y: 1 }],
    parTime: 16,
  },
];
