import type { LevelDef } from "../types";

// World 4 — Singularity Core: rotating platforms, fake exits, full combos.

export const world4: LevelDef[] = [
  {
    id: "w4-1",
    world: 4,
    index: 1,
    name: "Spin Cycle",
    ruleTaught: "This platform orbits a pivot — ride it, don't fight it.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    rotatingPlatforms: [{ id: "r1", cx: 13, cy: 4, radius: 4, speed: 1.1, armLen: 3 }],
    shards: [{ id: "s1", x: 13, y: 1 }],
    parTime: 14,
  },
  {
    id: "w4-2",
    world: 4,
    index: 2,
    name: "False Finish",
    ruleTaught: "The exit flag should be glowing gold — check before you celebrate.",
    twist: "That's a decoy. The real exit is further on.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    fakeExits: [{ id: "fx1", x: 12, y: 5 }],
    shards: [{ id: "s1", x: 18, y: 5 }],
    parTime: 11,
  },
  {
    id: "w4-3",
    world: 4,
    index: 3,
    name: "Everything At Once",
    ruleTaught: "Gravity flip, laser rhythm, and a spinning arm — read the whole room.",
    rows: [
      "##########................",
      "##########................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    gravityZones: [{ x: 9, y: 0, w: 6, h: 7 }],
    laserGates: [{ id: "l1", x: 18, y: 1, h: 6, axis: "vertical", onTime: 1, offTime: 1.2 }],
    rotatingPlatforms: [{ id: "r1", cx: 20, cy: 4, radius: 3, speed: 1.4, armLen: 2 }],
    shards: [{ id: "s1", x: 11, y: 1 }],
    parTime: 17,
  },
  {
    id: "w4-4",
    world: 4,
    index: 4,
    name: "Trust No Exit",
    ruleTaught: "Two flags glow gold. Only one is real.",
    twist: "The mimic is guarding the real one.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 22, y: 5 },
    fakeExits: [{ id: "fx1", x: 14, y: 5 }],
    mimicEnemies: [{ id: "m1", x: 19, y: 5, triggerRadius: 3, lungeSpeed: 250 }],
    shards: [{ id: "s1", x: 8, y: 5 }],
    parTime: 13,
  },
  {
    id: "w4-5",
    world: 4,
    index: 5,
    name: "Dark Orbit",
    ruleTaught: "The light-bridge, the freeze field, and a rotating platform — in sequence.",
    twist: "The rotating platform passes through the dark zone — time your ride.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    darkZones: [
      {
        id: "d1",
        x: 5,
        y: 0,
        w: 8,
        h: 7,
        bridgeTiles: [
          { x: 6, y: 5 },
          { x: 8, y: 5 },
          { x: 10, y: 5 },
        ],
      },
    ],
    freezeZones: [{ x: 14, y: 0, w: 4, h: 7 }],
    rotatingPlatforms: [{ id: "r1", cx: 19, cy: 4, radius: 3, speed: 1.2, armLen: 2 }],
    shards: [{ id: "s1", x: 8, y: 4 }],
    parTime: 18,
  },
  {
    id: "w4-6",
    world: 4,
    index: 6,
    name: "Core Breach",
    ruleTaught: "Everything you've learned, in one final run.",
    twist: "Nothing new — just no room for mistakes.",
    rows: [
      "##########........########",
      "##########........########",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    gravityZones: [{ x: 8, y: 0, w: 4, h: 7 }],
    reverseZones: [{ x: 12, y: 0, w: 3, h: 7 }],
    laserGates: [{ id: "l1", x: 17, y: 1, h: 6, axis: "vertical", onTime: 0.9, offTime: 1.1 }],
    fakeExits: [{ id: "fx1", x: 15, y: 5 }],
    mimicEnemies: [{ id: "m1", x: 20, y: 5, triggerRadius: 2.5, lungeSpeed: 270 }],
    shards: [{ id: "s1", x: 10, y: 1 }, { id: "s2", x: 21, y: 5 }],
    parTime: 20,
  },
];
