import type { LevelDef } from "../types";

// World 6 — Cyber Core: firewall sweeps (telegraphed traveling walls with a safe gap
// elsewhere in the column) layered onto the full toolkit built so far.

export const world6: LevelDef[] = [
  {
    id: "w6-1",
    world: 6,
    index: 1,
    name: "Firewall Init",
    ruleTaught: "The wall glows while charging, then sweeps across. Duck through the gap in its band.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [{ id: "f1", startX: 12, endX: 14, y: 3, h: 3, chargeTime: 1.2, sweepTime: 0.5 }],
    shards: [{ id: "s1", x: 12, y: 1 }],
    parTime: 12,
  },
  {
    id: "w6-2",
    world: 6,
    index: 2,
    name: "Cross Sweep",
    ruleTaught: "This one actually travels — time your run to be behind it, not in front.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [{ id: "f1", startX: 8, endX: 18, y: 3, h: 3, chargeTime: 1, sweepTime: 1.4 }],
    shards: [{ id: "s1", x: 20, y: 5 }],
    parTime: 14,
  },
  {
    id: "w6-3",
    world: 6,
    index: 3,
    name: "Grid & Blade",
    ruleTaught: "A sweeping wall over a spinning saw — pick your lane before you commit.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [{ id: "f1", startX: 9, endX: 17, y: 2, h: 3, chargeTime: 0.9, sweepTime: 1.2 }],
    rotatingPlatforms: [{ id: "r1", cx: 13, cy: 5, radius: 3, speed: 1.1, armLen: 2 }],
    shards: [{ id: "s1", x: 21, y: 5 }],
    parTime: 17,
  },
  {
    id: "w6-4",
    world: 6,
    index: 4,
    name: "Double Sweep",
    ruleTaught: "Two firewalls sweeping opposite directions — find the moment they're both clear.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [
      { id: "f1", startX: 8, endX: 16, y: 1, h: 3, chargeTime: 0.9, sweepTime: 1.1, phase: 0 },
      { id: "f2", startX: 18, endX: 10, y: 4, h: 3, chargeTime: 0.9, sweepTime: 1.1, phase: 0.5 },
    ],
    shards: [{ id: "s1", x: 13, y: 6 }],
    parTime: 19,
  },
  {
    id: "w6-5",
    world: 6,
    index: 5,
    name: "Encrypted Corridor",
    ruleTaught: "A firewall sweeping through a mimic's territory — don't let either surprise you.",
    twist: "The mimic waits right where the firewall's safe gap is — bait it before you cross.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [{ id: "f1", startX: 10, endX: 19, y: 2, h: 3, chargeTime: 1, sweepTime: 1.3 }],
    mimicEnemies: [{ id: "m1", x: 20, y: 5, triggerRadius: 3, lungeSpeed: 260 }],
    shards: [{ id: "s1", x: 15, y: 5 }],
    parTime: 20,
  },
  {
    id: "w6-6",
    world: 6,
    index: 6,
    name: "Core Lockdown",
    ruleTaught: "Everything from Cyber Core, chained together — no new tricks, just precision.",
    twist: "The last firewall syncs with a laser gate — only one clean beat gets you through.",
    rows: [
      "##########................",
      "##########................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....########.......####",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    firewallSweeps: [
      { id: "f1", startX: 9, endX: 17, y: 1, h: 3, chargeTime: 0.9, sweepTime: 1.1, phase: 0 },
      { id: "f2", startX: 19, endX: 22, y: 4, h: 3, chargeTime: 0.9, sweepTime: 0.9, phase: 0.4 },
    ],
    laserGates: [{ id: "l1", x: 14, y: 1, h: 6, axis: "vertical", onTime: 1, offTime: 1.1 }],
    rotatingPlatforms: [{ id: "r1", cx: 11, cy: 4, radius: 2.5, speed: 1.2, armLen: 2 }],
    shards: [{ id: "s1", x: 10, y: 1 }, { id: "s2", x: 21, y: 5 }],
    parTime: 23,
  },
];
