import type { LevelDef } from "../types";

// World 3 — The Undergate: freeze zones, dark/light bridges, exploding platforms, mimics.

export const world3: LevelDef[] = [
  {
    id: "w3-1",
    world: 3,
    index: 1,
    name: "Frozen Instant",
    ruleTaught: "Blue fields freeze every moving hazard while you're inside.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    laserGates: [{ id: "l1", x: 13, y: 1, h: 6, axis: "vertical", onTime: 1, offTime: 1 }],
    freezeZones: [{ x: 10, y: 0, w: 8, h: 7 }],
    shards: [{ id: "s1", x: 13, y: 5 }],
    parTime: 12,
  },
  {
    id: "w3-2",
    world: 3,
    index: 2,
    name: "Faint Light",
    ruleTaught: "In the dark, only tiles near you become solid ground.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    darkZones: [
      {
        id: "d1",
        x: 8,
        y: 0,
        w: 12,
        h: 7,
        bridgeTiles: [
          { x: 9, y: 5 },
          { x: 11, y: 5 },
          { x: 13, y: 5 },
          { x: 15, y: 5 },
          { x: 17, y: 5 },
        ],
      },
    ],
    shards: [{ id: "s1", x: 13, y: 4 }],
    parTime: 14,
  },
  {
    id: "w3-3",
    world: 3,
    index: 3,
    name: "Step Lightly",
    ruleTaught: "This platform crumbles a beat after you land on it.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    explodingPlatforms: [
      { id: "e1", x: 6, y: 5, w: 3, delay: 0.5, respawn: 2 },
      { id: "e2", x: 12, y: 5, w: 3, delay: 0.5, respawn: 2 },
      { id: "e3", x: 18, y: 5, w: 3, delay: 0.5, respawn: 2 },
    ],
    shards: [{ id: "s1", x: 14, y: 4 }],
    parTime: 11,
  },
  {
    id: "w3-4",
    world: 3,
    index: 4,
    name: "Something's Watching",
    ruleTaught: "That crate hasn't moved in a while... has it?",
    twist: "It wakes up and lunges the moment you get close.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    mimicEnemies: [{ id: "m1", x: 14, y: 5, triggerRadius: 3.5, lungeSpeed: 260 }],
    shards: [{ id: "s1", x: 20, y: 5 }],
    parTime: 12,
  },
  {
    id: "w3-5",
    world: 3,
    index: 5,
    name: "Dark Waters",
    ruleTaught: "Combine the light-bridge with a frozen laser.",
    twist: "The bridge only appears where you've already stepped — plan ahead.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    darkZones: [
      {
        id: "d1",
        x: 6,
        y: 0,
        w: 16,
        h: 7,
        bridgeTiles: [
          { x: 7, y: 5 },
          { x: 9, y: 5 },
          { x: 11, y: 5 },
          { x: 13, y: 5 },
          { x: 15, y: 5 },
          { x: 17, y: 5 },
          { x: 19, y: 5 },
        ],
      },
    ],
    laserGates: [{ id: "l1", x: 13, y: 1, h: 4, axis: "vertical", onTime: 0.8, offTime: 1.4 }],
    freezeZones: [{ x: 11, y: 0, w: 4, h: 7 }],
    shards: [{ id: "s1", x: 17, y: 4 }],
    parTime: 15,
  },
  {
    id: "w3-6",
    world: 3,
    index: 6,
    name: "The Long Fall",
    ruleTaught: "Crumbling steps over a mimic — don't linger anywhere.",
    twist: "The last platform is the mimic in disguise.",
    rows: [
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..........................",
      "..P.......................",
      "###....................###",
    ],
    playerStart: { x: 2, y: 5 },
    exit: { x: 24, y: 5 },
    explodingPlatforms: [
      { id: "e1", x: 6, y: 5, w: 2, delay: 0.45, respawn: 2 },
      { id: "e2", x: 10, y: 5, w: 2, delay: 0.45, respawn: 2 },
    ],
    mimicEnemies: [{ id: "m1", x: 16, y: 5, triggerRadius: 3, lungeSpeed: 280 }],
    shards: [{ id: "s1", x: 20, y: 4 }],
    parTime: 14,
  },
];
